feat: diff result validation (#11)

diff --git a/.github/workflows/pull-request-24.yml b/.github/workflows/pull-request-24.yml
--- a/.github/workflows/pull-request-24.yml
+++ b/.github/workflows/pull-request-24.yml
@@ -35,9 +35,93 @@ jobs:
         #tail -n +2 "code-list-new.csv" | sort >> code-list-new-sorted.csv
         # Generate commit message using csv-diff
         csv-diff code-list-old.csv code-list-new.csv --key=Code --singular=record --plural=records > message.txt
+        csv-diff code-list-old.csv code-list-new.csv --key=Code --singular=record --plural=records --json > message.json
         cat message.txt
         # todo: add check for message.txt content
         # mv code-list-new-sorted.csv "CRL/Rec24/current/code-list.csv"
+
+    - run: jq -c '.added | select (.!=null) | .[] | select (.CI != "+")' < message.json >> errors.txt
+    - run: |
+        [ -s errors.txt ] && sed -i '1s/^/A new code list value was added, but CI was not set to `+`:\n/' errors.txt || rm -f errors.txt
+    
+    - run: jq -c '.removed | select (.!=null) | .[]' < message.json >> errors-removed.txt
+    - run: |
+        [ -s errors-removed.txt ] && \
+          echo 'No lines should be removed, set CI to `X` instead:' >> errors.txt && \
+          cat errors-removed.txt >> errors.txt || rm -f errors-removed.txt
+
+    - run: jq -c '.changed | select (.!=null) | .[] | select (.changes.CI != ["","="] and .changes.CI != ["","X"] and .changes.CI != ["","|"] and .changes.CI != ["","#"])' < message.json >> errors-CI.txt
+    - run: |
+        [ -s errors-CI.txt ] && \
+          echo 'Unexpected value set for CI:' >> errors.txt && \
+          cat errors-CI.txt >> errors.txt || rm -f errors-CI.txt
+      
+
+    - run: jq -c '.changed | select (.!=null) | .[] | select (.changes.CI == ["","="]) | if (.changes != {CI:["","="]}) then . else null end | select (.!=null)' < message.json >> errors-reinstated.txt
+    - run: |
+        [ -s errors-reinstated.txt ] && \
+          echo 'Only CI should be changed for the record marked as reinstated:' >> errors.txt && \
+          cat errors-reinstated.txt >> errors.txt || rm -f errors-reinstated.txt
+
+          
+    - run: jq -c '.changed | select (.!=null) | .[] | select (.changes.CI == ["","X"]) | if (.changes != {CI:["","X"]}) then . else null end | select (.!=null)' < message.json >> errors-deleted.txt
+    - run: |
+        [ -s errors-deleted.txt ] && \
+          echo 'Only CI should be changed for the record marked as deleted:' >> errors.txt && \
+          cat errors-deleted.txt >> errors.txt || rm -f errors-deleted.txt
+
+    - run: jq -c '.changed | select (.!=null) | .[] | select (.changes.CI == ["","|"] and (.changes.Description == null or .changes.Name != null))' < message.json >> errors-changed-description.txt
+    - run: |
+        [ -s errors-changed-description.txt ] && \
+          echo 'The description needs to be changed for the record with CI set to `|`:' >> errors.txt && \
+          cat errors-changed-description.txt >> errors.txt || rm -f errors-changed-description.txt
+                
+    - run: jq -c '.changed | select (.!=null) | .[] | select (.changes.CI == ["","#"] and (.changes.Description != null or .changes.Name == null))' < message.json >> errors-changed-description.txt
+    - run: |
+        [ -s errors-changed-name.txt ] && \
+          echo 'The name needs to be changed for the record with CI set to `#`:' >> errors.txt && \
+          cat errors-changed-name.txt >> errors.txt || rm -f errors-changed-name.txt
+      
+
+
+    - name: Set variables
+      if: ${{ hashFiles('errors.txt') != '' }}
+      run: |
+          {
+            echo 'ERRORS<<EOF'
+            cat errors.txt
+            echo EOF
+          } >> "$GITHUB_ENV"
+    - name: Check errors.txt file
+      if: ${{ hashFiles('errors.txt') != '' }}
+      uses: mb2dev/github-action-comment-pull-request@1.0.0
+      with:
+        message: |
+              ${{ env.ERRORS }}
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      
+    - name: Fail check if there are errors
+      if: ${{ hashFiles('errors.txt') != '' }}
+      run: echo "Validation failed" && exit 1      
+        
+    - name: Set variables
+      if: ${{ hashFiles('message.txt') != '' }}
+      run: |
+        {
+          echo 'MESSAGE<<EOF'
+          cat message.txt
+          echo EOF
+        } >> "$GITHUB_ENV"
+          
+    - name: Comment a pull_request
+      if: ${{ hashFiles('message.txt') != '' }}
+      uses: mb2dev/github-action-comment-pull-request@1.0.0
+      with:
+        message: |
+              message:
+              ${{ env.MESSAGE }}
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      
     - name: Commit and push if it changed
       run: |-
         git config user.name "Automated"
